### ISSUE TITLE
utils.lisp fails to compile on sbcl 2.4.4 with safety 3, debug 3

### ISSUE THREAD

**Issue by K1D77A** [fare/fare-utils#2]
Hey,
I have just installed sbcl 2.4.4 with --fancy, however when I have run into an issue when trying to build a project of mine using docker. 
The trace is here: https://plaster.tymoon.eu/view/4264#4264
I then loaded up a fresh sbcl 2.4.4, quickload fare-utils  (which works) but I then manually compile utils.lisp and get the same error
![image](https://github.com/fare/fare-utils/assets/10334164/7a544beb-de39-4e0a-9792-b079375b9536)

To fix I have to remove 
```lisp
(sb-ext:restrict-compiler-policy 'safety 3 3)
(sb-ext:restrict-compiler-policy 'debug 3 3)
(sb-ext:restrict-compiler-policy 'space 1 1)
(sb-ext:restrict-compiler-policy 'speed 0 0)
```
from my .sbclrc 
I'm not sure if this is actually a problem with your utils or if the problem lies with something like Slynk or SBCL itself. 

A full expanded version of the stack trace is here: https://plaster.tymoon.eu/view/4265#4265

Thanks.

**Comment by K1D77A** [comment]
After a little more testing I only had to remove the 'speed 0 entry.

**Comment by K1D77A** [comment]
Oh also I was using 2.3.5 before and didn't have this problem.

**Comment by fare** [comment]
I don't see a problem on sbcl 2.4.3.

You could try to dichotomize utils.lisp to see where exactly it fails.

Looks like the error involves some fixnum that isn't a fixnum, whereas the file contains nothing about fixnums. Might be a compiler bug.

**Comment by fare** [comment]
Do you have steps to reproduce?

**Comment by K1D77A** [comment]
> Do you have steps to reproduce?

Not beyond what I already posted.
I updated to 2.4.4 by compiling from source with --fancy and 2GB dynamic 
I then launch cl with sly, (ql:quickload :fare-utils) and then compile with c-c-h  c-c c-c the utils.lisp file. 
And I had 
```lisp
(sb-ext:restrict-compiler-policy 'safety 3 3)
(sb-ext:restrict-compiler-policy 'debug 3 3)
(sb-ext:restrict-compiler-policy 'space 1 1)
(sb-ext:restrict-compiler-policy 'speed 0 0)
```
in my .sbclrc

**Comment by K1D77A** [comment]
![image](https://github.com/fare/fare-utils/assets/10334164/3548c8df-2932-4f90-a293-82e167c636e6)

**Comment by K1D77A** [comment]
Looks like a compiler bug then :+1:  Thanks
